### ISSUE TITLE
how to train cifar10?

### ISSUE THREAD

**Issue by zihaozhang9** [renqianluo/NAO_pytorch#1]
Is the following command used?
`nvidia-smi
MODEL=imagenet
OUTPUT_DIR=exp/$MODEL
DATA_DIR=imagenet/raw-data

mkdir -p $OUTPUT_DIR

fixed_arc="0 7 1 15 2 8 1 7 0 6 1 7 0 8 4 7 1 5 0 7 0 7 1 13 0 6 0 14 0 9 1 10 0 14 2 6 1 11 0 7"

python train_cifar.py \
  --data=$DATA_DIR \
  --output_dir=$OUTPUT_DIR \
  --batch_size=128 \
  --epochs=250 \
  --arch="$fixed_arc" \
  --channels=42 \
  --use_aux_head \
  --lr=0.1 \
  --keep_prob=1.0 \
  --drop_path_keep_prob=1.0 | tee -a $OUTPUT_DIR/train.log`

**Comment by renqianluo** [comment]
@zihaozhang9 these hyper parameters are for imagenet training. for cifar, just use the command below as in the original NAO repo:
`nvidia-smi`
`MODEL=cifar10`
`OUTPUT_DIR=exp/$MODEL`
`DATA_DIR=$HOME/data`

`mkdir -p $OUTPUT_DIR`

`fixed_arc="0 7 1 15 2 8 1 7 0 6 1 7 0 8 4 7 1 5 0 7 0 7 1 13 0 6 0 14 0 9 1 10 0 14 2 6 1 11 0 7"`

`python train_cifar.py \`
`  --data=$DATA_DIR \`
`  --output_dir=$OUTPUT_DIR \`
`  --batch_size=128 \`
`  --arch="$fixed_arc" \`
`  --channels=128 \`
`  --use_aux_head \`
`  --cutout_size=16 \`
`  --l2_reg=5e-4 \`
`  --keep_prob=0.6 \`
`  --drop_path_keep_prob=0.7 | tee -a $OUTPUT_DIR/train.log`

This is the biggest model as in the paper, which would give you a final test error rate of about 2.0 +- 0.05, and should run on 4 cards.
You can also set `--channels` to 36 for small model, which can run on single card, and should give you a final test error rate of about 2.5 +- 0.05

BTW, this repo is not finalized, and I will update more scripts

**Comment by zihaozhang9** [comment]
> @zihaozhang9 these hyper parameters are for imagenet training. for cifar, just use the command below as in the original NAO repo:
> `nvidia-smi`
> `MODEL=cifar10`
> `OUTPUT_DIR=exp/$MODEL`
> `DATA_DIR=$HOME/data`
> 
> `mkdir -p $OUTPUT_DIR`
> 
> `fixed_arc="0 7 1 15 2 8 1 7 0 6 1 7 0 8 4 7 1 5 0 7 0 7 1 13 0 6 0 14 0 9 1 10 0 14 2 6 1 11 0 7"`
> 
> `python train_cifar.py \`
> ` --data=$DATA_DIR \`
> ` --output_dir=$OUTPUT_DIR \`
> ` --batch_size=128 \`
> ` --arch="$fixed_arc" \`
> ` --channels=128 \`
> ` --use_aux_head \`
> ` --cutout_size=16 \`
> ` --l2_reg=5e-4 \`
> ` --keep_prob=0.6 \`
> ` --drop_path_keep_prob=0.7 | tee -a $OUTPUT_DIR/train.log`
> 
> This is the biggest model as in the paper, which would give you a final test error rate of about 2.0 +- 0.05, and should run on 4 cards.
> You can also set `--channels` to 36 for small model, which can run on single card, and should give you a final test error rate of about 2.5 +- 0.05
> 
> BTW, this repo is not finalized, and I will update more scripts

ok!I am running train_search.py.

`export PYTHONPATH=./:$PYTHONPATH
MODEL=search_cifar10
MODEL_DIR=models/$MODEL
LOG_DIR=logs
DATA_DIR=data/cifar10

mkdir -p $MODEL_DIR/child
mkdir -p $MODEL_DIR/controller
mkdir -p $LOG_DIR

python -u train_search.py \
  --child_cutout_size=16 \
  --output_dir=$MODEL_DIR \
  --child_sample_policy=uniform \
  --child_batch_size=64 \
  --child_l2_reg=1e-4 \
  --child_keep_prob=0.90 \
  --child_drop_path_keep_prob=0.60 \
  --child_lr_max=0.05 \
  --child_lr_min=0.0005 \
  --child_eval_batch_size=128 \
  --controller_encoder_vocab_size=12 \
  --controller_decoder_vocab_size=12 \
  --controller_encoder_emb_size=48 \
  --controller_encoder_hidden_size=96 \
  --controller_decoder_hidden_size=96 \
  --controller_mlp_hidden_size=100 \
  --controller_mlp_dropout=0.1 \
  --controller_source_length=40 \
  --controller_encoder_length=20 \
  --controller_decoder_length=40 \
  --controller_optimizer=adam \
  --controller_lr=0.001 \
  --controller_batch_size=32 | tee $LOG_DIR/train.$MODEL.log`
